/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yous
 */
public class GUI extends javax.swing.JFrame {

    private static partsDB db;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

        chooseByCarModel.setVisible(false);
        chooseByVendor.setVisible(false);
        partnumberdropdown.setEnabled(false);
        nextButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseByCarModel = new javax.swing.JPanel();
        choosecarPanel = new java.awt.Panel();
        makerLabel = new javax.swing.JLabel();
        carMakerDropdown = new javax.swing.JComboBox();
        modelLabel = new javax.swing.JLabel();
        carModelDropdown = new javax.swing.JComboBox();
        yearLabel = new javax.swing.JLabel();
        engineLabel = new javax.swing.JLabel();
        carpartnumberLabel = new javax.swing.JLabel();
        yearDropdown = new javax.swing.JComboBox();
        engineDropDown = new javax.swing.JComboBox();
        partnumberdropdown = new javax.swing.JComboBox();
        carHomeLabel = new javax.swing.JLabel();
        choosebycarmodelLabel = new javax.swing.JLabel();
        nextButtonPanel = new java.awt.Panel();
        nextButton = new javax.swing.JButton();
        homeScreenPage = new javax.swing.JPanel();
        searchbyLabel = new javax.swing.JLabel();
        carmodelButton = new javax.swing.JButton();
        vendorButton = new javax.swing.JButton();
        chooseByVendor = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        vendorLabel = new javax.swing.JLabel();
        partnumberdropdownLabel = new javax.swing.JLabel();
        vendordropdownLabel = new javax.swing.JLabel();
        vendorDropdown = new javax.swing.JComboBox();
        partNumberDropdown = new javax.swing.JComboBox();
        vendorLeftPanel = new javax.swing.JPanel();
        partnumberLabel = new javax.swing.JLabel();
        coreLabel = new javax.swing.JLabel();
        inheadLabel = new javax.swing.JLabel();
        outheadLabel = new javax.swing.JLabel();
        inconLabel = new javax.swing.JLabel();
        partnumberText = new javax.swing.JLabel();
        coreText = new javax.swing.JLabel();
        inheadText = new javax.swing.JLabel();
        outheadText = new javax.swing.JLabel();
        inconText = new javax.swing.JLabel();
        vendorRightPanel = new javax.swing.JPanel();
        ouconLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        oilcoolLabel = new javax.swing.JLabel();
        tmountLabel = new javax.swing.JLabel();
        ouconText = new javax.swing.JLabel();
        tmountText = new javax.swing.JLabel();
        oilcoolText = new javax.swing.JLabel();
        priceText = new javax.swing.JLabel();
        amountText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Store");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(736, 200));
        setMinimumSize(new java.awt.Dimension(736, 320));
        setPreferredSize(new java.awt.Dimension(720, 320));

        chooseByCarModel.setBackground(new java.awt.Color(255, 255, 255));
        chooseByCarModel.setMaximumSize(new java.awt.Dimension(720, 320));
        chooseByCarModel.setMinimumSize(new java.awt.Dimension(720, 320));
        chooseByCarModel.setPreferredSize(new java.awt.Dimension(720, 320));
        chooseByCarModel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choosecarPanel.setBackground(new java.awt.Color(255, 255, 255));
        choosecarPanel.setMaximumSize(new java.awt.Dimension(720, 200));
        choosecarPanel.setMinimumSize(new java.awt.Dimension(720, 200));
        choosecarPanel.setPreferredSize(new java.awt.Dimension(720, 200));

        makerLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        makerLabel.setForeground(new java.awt.Color(0, 153, 204));
        makerLabel.setText("Maker");

        carMakerDropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        carMakerDropdown.setMaximumRowCount(16);
        carMakerDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUK BUICK", "CAD CADILLAC", "CHE CHEVROLET", "CRY CHRYSLER", "FDT FORD LIGHT TRUCK AND VAN", "FOR FORD", "GMC CHEVROLET & GMC TRUCK & VAN", "INT INTERNATIONAL TRUCK (I.H.C.)", "ISU ISUZU", "LIN LINCOLN", "MZD MAZDA", "OLD OLDSMOBILE", "POR PORSCHE", "REN RENAULT", "SAB SAAB", "SUB SUBARU", "TOY TOYOTA", "UPS UPS", "VOL VOLKSWAGEN" }));
        carMakerDropdown.setToolTipText("");
        carMakerDropdown.setBorder(null);
        carMakerDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carMakerDropdownActionPerformed(evt);
            }
        });

        modelLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        modelLabel.setForeground(new java.awt.Color(0, 153, 204));
        modelLabel.setText("Model");

        carModelDropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        carModelDropdown.setMaximumRowCount(16);
        carModelDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select model -" }));
        carModelDropdown.setToolTipText("");
        carModelDropdown.setBorder(null);
        carModelDropdown.setEnabled(false);
        carModelDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelDropdownActionPerformed(evt);
            }
        });

        yearLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(0, 153, 204));
        yearLabel.setText("Year");

        engineLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        engineLabel.setForeground(new java.awt.Color(0, 153, 204));
        engineLabel.setText("Engine");

        carpartnumberLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        carpartnumberLabel.setForeground(new java.awt.Color(0, 153, 204));
        carpartnumberLabel.setText("Part number");

        yearDropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        yearDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select year -" }));
        yearDropdown.setToolTipText("");
        yearDropdown.setEnabled(false);
        yearDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearDropdownActionPerformed(evt);
            }
        });

        engineDropDown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        engineDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select engine -" }));
        engineDropDown.setToolTipText("");
        engineDropDown.setEnabled(false);
        engineDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineDropDownActionPerformed(evt);
            }
        });

        partnumberdropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        partnumberdropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select part number -", " " }));
        partnumberdropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partnumberdropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choosecarPanelLayout = new javax.swing.GroupLayout(choosecarPanel);
        choosecarPanel.setLayout(choosecarPanelLayout);
        choosecarPanelLayout.setHorizontalGroup(
            choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosecarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(choosecarPanelLayout.createSequentialGroup()
                            .addComponent(engineLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                            .addComponent(engineDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choosecarPanelLayout.createSequentialGroup()
                            .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modelLabel)
                                .addComponent(yearLabel)
                                .addComponent(makerLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(carMakerDropdown, 0, 235, Short.MAX_VALUE)
                                .addComponent(yearDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carModelDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(choosecarPanelLayout.createSequentialGroup()
                        .addComponent(carpartnumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(partnumberdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        choosecarPanelLayout.setVerticalGroup(
            choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosecarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makerLabel)
                    .addComponent(carMakerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(carModelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engineLabel)
                    .addComponent(engineDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(choosecarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carpartnumberLabel)
                    .addComponent(partnumberdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        chooseByCarModel.add(choosecarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 200));

        carHomeLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        carHomeLabel.setForeground(new java.awt.Color(204, 204, 204));
        carHomeLabel.setText("Home");
        carHomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carHomeLabelMouseClicked(evt);
            }
        });
        chooseByCarModel.add(carHomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 10, 70, -1));

        choosebycarmodelLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        choosebycarmodelLabel.setForeground(new java.awt.Color(153, 153, 153));
        choosebycarmodelLabel.setText("Choose by Car Model");
        chooseByCarModel.add(choosebycarmodelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 0, 280, 50));

        nextButtonPanel.setBackground(new java.awt.Color(247, 149, 62));
        nextButtonPanel.setMaximumSize(new java.awt.Dimension(720, 25));
        nextButtonPanel.setMinimumSize(new java.awt.Dimension(720, 25));
        nextButtonPanel.setPreferredSize(new java.awt.Dimension(720, 25));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next icon.jpg"))); // NOI18N
        nextButton.setAlignmentY(0.0F);
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next icon hover.jpg"))); // NOI18N
        nextButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nextButton.setMaximumSize(new java.awt.Dimension(80, 25));
        nextButton.setMinimumSize(new java.awt.Dimension(80, 25));
        nextButton.setPreferredSize(new java.awt.Dimension(80, 25));
        nextButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next icon hover.jpg"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nextButtonPanelLayout = new javax.swing.GroupLayout(nextButtonPanel);
        nextButtonPanel.setLayout(nextButtonPanelLayout);
        nextButtonPanelLayout.setHorizontalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addContainerGap(630, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nextButtonPanelLayout.setVerticalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        chooseByCarModel.add(nextButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 295, 720, -1));

        homeScreenPage.setBackground(new java.awt.Color(255, 255, 255));
        homeScreenPage.setMaximumSize(new java.awt.Dimension(720, 320));
        homeScreenPage.setMinimumSize(new java.awt.Dimension(720, 320));
        homeScreenPage.setPreferredSize(new java.awt.Dimension(720, 320));
        homeScreenPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbyLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        searchbyLabel.setForeground(new java.awt.Color(153, 153, 153));
        searchbyLabel.setText("Search by");
        homeScreenPage.add(searchbyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        carmodelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Car Model.jpg"))); // NOI18N
        carmodelButton.setBorder(null);
        carmodelButton.setBorderPainted(false);
        carmodelButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        carmodelButton.setMaximumSize(new java.awt.Dimension(200, 300));
        carmodelButton.setMinimumSize(new java.awt.Dimension(200, 300));
        carmodelButton.setPreferredSize(new java.awt.Dimension(200, 300));
        carmodelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Car Model Hover.jpg"))); // NOI18N
        carmodelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carmodelButtonActionPerformed(evt);
            }
        });
        homeScreenPage.add(carmodelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 11, -1, -1));

        vendorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vendor.jpg"))); // NOI18N
        vendorButton.setBorder(null);
        vendorButton.setBorderPainted(false);
        vendorButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        vendorButton.setMaximumSize(new java.awt.Dimension(200, 300));
        vendorButton.setMinimumSize(new java.awt.Dimension(200, 300));
        vendorButton.setPreferredSize(new java.awt.Dimension(200, 300));
        vendorButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vendor Hover.jpg"))); // NOI18N
        vendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorButtonActionPerformed(evt);
            }
        });
        homeScreenPage.add(vendorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 11, -1, -1));

        chooseByVendor.setBackground(new java.awt.Color(255, 255, 255));
        chooseByVendor.setMaximumSize(new java.awt.Dimension(700, 320));
        chooseByVendor.setMinimumSize(new java.awt.Dimension(700, 320));
        chooseByVendor.setPreferredSize(new java.awt.Dimension(720, 320));
        chooseByVendor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(204, 204, 204));
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });
        chooseByVendor.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 10, 70, -1));

        vendorLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        vendorLabel.setForeground(new java.awt.Color(153, 153, 153));
        vendorLabel.setText("Choose By Vendor");
        chooseByVendor.add(vendorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 0, 240, 50));

        partnumberdropdownLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        partnumberdropdownLabel.setForeground(new java.awt.Color(0, 153, 204));
        partnumberdropdownLabel.setText("Part number");
        chooseByVendor.add(partnumberdropdownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        vendordropdownLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        vendordropdownLabel.setForeground(new java.awt.Color(0, 153, 204));
        vendordropdownLabel.setText("Vendor");
        chooseByVendor.add(vendordropdownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        vendorDropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        vendorDropdown.setMaximumRowCount(16);
        vendorDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select vendor -", "RDIMARS", "RDIMBEH", "RDIMDAN", "RDIMMOD" }));
        vendorDropdown.setToolTipText("");
        vendorDropdown.setBorder(null);
        vendorDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorDropdownActionPerformed(evt);
            }
        });
        chooseByVendor.add(vendorDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 241, -1));

        partNumberDropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        partNumberDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select part number -" }));
        partNumberDropdown.setToolTipText("");
        partNumberDropdown.setEnabled(false);
        partNumberDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partNumberDropdownActionPerformed(evt);
            }
        });
        chooseByVendor.add(partNumberDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, -1));

        vendorLeftPanel.setBackground(new java.awt.Color(255, 255, 255));

        partnumberLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        partnumberLabel.setForeground(new java.awt.Color(0, 153, 204));
        partnumberLabel.setText("Part number");

        coreLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        coreLabel.setForeground(new java.awt.Color(0, 153, 204));
        coreLabel.setText("Core");

        inheadLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        inheadLabel.setForeground(new java.awt.Color(0, 153, 204));
        inheadLabel.setText("Inhead");

        outheadLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        outheadLabel.setForeground(new java.awt.Color(0, 153, 204));
        outheadLabel.setText("Outhead");

        inconLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        inconLabel.setForeground(new java.awt.Color(0, 153, 204));
        inconLabel.setText("Incon");

        partnumberText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        partnumberText.setForeground(new java.awt.Color(153, 153, 153));
        partnumberText.setText("          ");

        coreText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        coreText.setForeground(new java.awt.Color(153, 153, 153));
        coreText.setText("          ");

        inheadText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        inheadText.setForeground(new java.awt.Color(153, 153, 153));
        inheadText.setText("          ");

        outheadText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        outheadText.setForeground(new java.awt.Color(153, 153, 153));
        outheadText.setText("          ");

        inconText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        inconText.setForeground(new java.awt.Color(153, 153, 153));
        inconText.setText("          ");

        javax.swing.GroupLayout vendorLeftPanelLayout = new javax.swing.GroupLayout(vendorLeftPanel);
        vendorLeftPanel.setLayout(vendorLeftPanelLayout);
        vendorLeftPanelLayout.setHorizontalGroup(
            vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                        .addComponent(inheadLabel)
                        .addGap(58, 58, 58)
                        .addComponent(inheadText))
                    .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                        .addComponent(outheadLabel)
                        .addGap(43, 43, 43)
                        .addComponent(outheadText))
                    .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                        .addComponent(inconLabel)
                        .addGap(68, 68, 68)
                        .addComponent(inconText))
                    .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                            .addComponent(coreLabel)
                            .addGap(74, 74, 74)
                            .addComponent(coreText))
                        .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                            .addComponent(partnumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(partnumberText))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        vendorLeftPanelLayout.setVerticalGroup(
            vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partnumberLabel)
                    .addComponent(partnumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coreText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vendorLeftPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(coreLabel)))
                .addGap(15, 15, 15)
                .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inheadLabel)
                    .addComponent(inheadText))
                .addGap(15, 15, 15)
                .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outheadLabel)
                    .addComponent(outheadText))
                .addGap(15, 15, 15)
                .addGroup(vendorLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inconLabel)
                    .addComponent(inconText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chooseByVendor.add(vendorLeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 400, 210));

        vendorRightPanel.setBackground(new java.awt.Color(255, 255, 255));

        ouconLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ouconLabel.setForeground(new java.awt.Color(0, 153, 204));
        ouconLabel.setText("Oucon");

        amountLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(0, 153, 204));
        amountLabel.setText("Amount");

        priceLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 153, 204));
        priceLabel.setText("Price");

        oilcoolLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        oilcoolLabel.setForeground(new java.awt.Color(0, 153, 204));
        oilcoolLabel.setText("Oilcool");

        tmountLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tmountLabel.setForeground(new java.awt.Color(0, 153, 204));
        tmountLabel.setText("Tmount");

        ouconText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ouconText.setForeground(new java.awt.Color(153, 153, 153));
        ouconText.setText("          ");

        tmountText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tmountText.setForeground(new java.awt.Color(153, 153, 153));
        tmountText.setText("          ");

        oilcoolText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        oilcoolText.setForeground(new java.awt.Color(153, 153, 153));
        oilcoolText.setText("          ");

        priceText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        priceText.setForeground(new java.awt.Color(153, 153, 153));
        priceText.setText("          ");

        amountText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        amountText.setForeground(new java.awt.Color(153, 153, 153));
        amountText.setText("          ");

        javax.swing.GroupLayout vendorRightPanelLayout = new javax.swing.GroupLayout(vendorRightPanel);
        vendorRightPanel.setLayout(vendorRightPanelLayout);
        vendorRightPanelLayout.setHorizontalGroup(
            vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorRightPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorRightPanelLayout.createSequentialGroup()
                        .addComponent(oilcoolLabel)
                        .addGap(26, 26, 26)
                        .addComponent(oilcoolText))
                    .addGroup(vendorRightPanelLayout.createSequentialGroup()
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(priceText))
                    .addGroup(vendorRightPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(amountLabel)
                        .addGap(18, 18, 18)
                        .addComponent(amountText))
                    .addGroup(vendorRightPanelLayout.createSequentialGroup()
                        .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tmountLabel)
                            .addComponent(ouconLabel))
                        .addGap(21, 21, 21)
                        .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ouconText)
                            .addComponent(tmountText))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        vendorRightPanelLayout.setVerticalGroup(
            vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouconLabel)
                    .addComponent(ouconText))
                .addGap(15, 15, 15)
                .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tmountLabel)
                    .addComponent(tmountText))
                .addGap(19, 19, 19)
                .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oilcoolLabel)
                    .addComponent(oilcoolText))
                .addGap(15, 15, 15)
                .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceText))
                .addGap(14, 14, 14)
                .addGroup(vendorRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountText))
                .addGap(11, 11, 11))
        );

        chooseByVendor.add(vendorRightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 310, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeScreenPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chooseByCarModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(chooseByVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeScreenPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(752, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(chooseByCarModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(752, 752, 752)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(chooseByVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 752, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-666)/2, (screenSize.height-358)/2, 666, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void vendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorButtonActionPerformed
        homeScreenPage.setVisible(false);
        chooseByCarModel.setVisible(false);
        chooseByVendor.setVisible(true);

    }//GEN-LAST:event_vendorButtonActionPerformed

    private void carmodelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carmodelButtonActionPerformed
        homeScreenPage.setVisible(false);
        chooseByCarModel.setVisible(true);
    }//GEN-LAST:event_carmodelButtonActionPerformed

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        switchVisibility(chooseByVendor, homeScreenPage);
    }//GEN-LAST:event_homeLabelMouseClicked

    private void vendorDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorDropdownActionPerformed
        partNumberDropdown.setEnabled(true);

        try {
            partsDB DBC = new partsDB("jdbc:oracle:thin:@localhost:1521:ORCL", "scott", "tiger");

            Statement stmnt = DBC.getDBConnection().createStatement();
            ResultSet rs = null;
            String getPart = (String) vendorDropdown.getSelectedItem();

            String sql = "select distinct p_number from " + getPart;
            rs = stmnt.executeQuery(sql);
            while (rs.next()) {
                String name = rs.getString(1);
                partNumberDropdown.addItem(name);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //db.setVendor(vendorDropdown.getSelected...
    }//GEN-LAST:event_vendorDropdownActionPerformed

    private void partNumberDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partNumberDropdownActionPerformed
        //db.setPartNumber(partNumberDropdown.getSelectedObjects());
        //jButton6.setEnabled(true);
        ResultSet rs = null;
        if (vendorDropdown.getSelectedItem() != null && partNumberDropdown.getSelectedItem() != null) {
            try {
                partsDB DBC = new partsDB("jdbc:oracle:thin:@localhost:1521:ORCL", "scott", "tiger");
                String getNumber = (String) partNumberDropdown.getSelectedItem();
                String getPart = (String) vendorDropdown.getSelectedItem();
                Statement stmnt = DBC.getDBConnection().createStatement();


                rs = stmnt.executeQuery("select * from " + getPart + " where "
                        + "p_number = '" + getNumber + "'");

                if (rs.next()) {
                    partnumberText.setText(rs.getString(1));
                    coreText.setText(rs.getString(2));
                    inheadText.setText(rs.getString(3));
                    outheadText.setText(rs.getString(4));
                    inconText.setText(rs.getString(5));
                    ouconText.setText(rs.getString(6));
                    tmountText.setText(rs.getString(7));
                    oilcoolText.setText(rs.getString(8));
                    priceText.setText(rs.getString(9));
                    amountText.setText(rs.getString(10));
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_partNumberDropdownActionPerformed

    private void partnumberdropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partnumberdropdownActionPerformed

    }//GEN-LAST:event_partnumberdropdownActionPerformed

    private void engineDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineDropDownActionPerformed
        partnumberdropdown.setEnabled(true);

        try {
            partsDB DBC = new partsDB("jdbc:oracle:thin:@localhost:1521:ORCL", "scott", "tiger");

            Statement stmnt = DBC.getDBConnection().createStatement();
            ResultSet rs = null;
            String getPart = (String) carMakerDropdown.getSelectedItem();
            String getModel = (String) carModelDropdown.getSelectedItem();
            String getYear = (String) yearDropdown.getSelectedItem();
            String sql = "select RLINK from apl" + getPart.substring(0, 3) + " where model = '" + getModel + "'"
            + "AND year ='" + getYear + "'";
            rs = stmnt.executeQuery(sql);
            while (rs.next()) {
                String name = rs.getString(1);
                partnumberdropdown.addItem(name);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        //        jButton4.setEnabled(true);
        //        db.setEngine(engineDropDown.getSelectedItem().toString());
    }//GEN-LAST:event_engineDropDownActionPerformed

    private void yearDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearDropdownActionPerformed
        engineDropDown.setEnabled(true);

        try {
            partsDB DBC = new partsDB("jdbc:oracle:thin:@localhost:1521:ORCL", "scott", "tiger");

            Statement stmnt = DBC.getDBConnection().createStatement();
            ResultSet rs = null;
            String getPart = (String) carMakerDropdown.getSelectedItem();
            String getModel = (String) carModelDropdown.getSelectedItem();
            String getYear = (String) yearDropdown.getSelectedItem();
            String sql = "select ENGINE_TYPE from apl" + getPart.substring(0, 3) + " where model = '" + getModel + "'"
            + "AND year ='" + getYear + "'";
            rs = stmnt.executeQuery(sql);
            while (rs.next()) {
                String name = rs.getString(1);
                engineDropDown.addItem(name);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        //        String year = yearDropdown.getSelectedItem().toString();
        //        db.setYear(year);
        //        String[] engines = db.getEngine();
        //        for(String engine : engines) {
            //            engineDropDown.addItem(engine);
            //        }
        //        engineDropDown.setEnabled(true);
        //        db.setYear(yearDropdown.getSelectedItem().toString());
    }//GEN-LAST:event_yearDropdownActionPerformed

    private void carModelDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelDropdownActionPerformed

        yearDropdown.setEnabled(true);

        try {
            partsDB DBC = new partsDB("jdbc:oracle:thin:@localhost:1521:ORCL", "scott", "tiger");

            Statement stmnt = DBC.getDBConnection().createStatement();
            ResultSet rs = null;
            String getPart = (String) carMakerDropdown.getSelectedItem();
            String getModel = (String) carModelDropdown.getSelectedItem();
            String sql = "select year from apl" + getPart.substring(0, 3) + " where model = '" + getModel + "'";
            rs = stmnt.executeQuery(sql);
            while (rs.next()) {
                String name = rs.getString(1);
                yearDropdown.addItem(name);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //        String model = carModelDropdown.getSelectedItem().toString();
        //        db.setModel(model);
        //        String[] years = db.getYear();
        //        //yearDropdown.removeAllItems();
        //        for (String year : years) {
            //            yearDropdown.addItem(year);
            //        }
        //        yearDropdown.setEnabled(true);
    }//GEN-LAST:event_carModelDropdownActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        chooseByCarModel.setVisible(false);
        DefaultTableModel model = new DefaultTableModel();

        ArrayList<HashMap> parts = db.getParts();

        for (HashMap<String, String> row : parts) {
            String[] rowArray = new String[row.size()];
            int i = 0;
            Iterator column = row.entrySet().iterator();
            while (column.hasNext()) {
                Entry current = (Map.Entry) column.next();
                rowArray[i] = current.getValue().toString();
                i++;
            }
            model.addRow(rowArray);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    private void carHomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carHomeLabelMouseClicked
        switchVisibility(chooseByCarModel, homeScreenPage);
    }//GEN-LAST:event_carHomeLabelMouseClicked

    private void carMakerDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carMakerDropdownActionPerformed

        carModelDropdown.setEnabled(true);

        try {
            partsDB DBC = new partsDB("jdbc:oracle:thin:@localhost:1521:ORCL", "scott", "tiger");

            Statement stmnt = DBC.getDBConnection().createStatement();
            ResultSet rs = null;
            String getPart = (String) carMakerDropdown.getSelectedItem();

            String sql = "select model from apl" + getPart.substring(0, 3);
            rs = stmnt.executeQuery(sql);
            while (rs.next()) {
                String name = rs.getString(1);
                carModelDropdown.addItem(name);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //        carModelDropdown.removeAllItems();
        //        try {
            //             TODO add your handling code here:
            //            db = new partsDB("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
            //        } catch (SQLException ex) {
            //            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        //        String maker = carMakerDropdown.getSelectedItem().toString().substring(0, 3);
        //        db.setMaker(maker);
        //        String[] models = db.getModel();
        //
        //        for (String model : models) {
            //            carModelDropdown.addItem(model.toString());
            //        }
        //        carModelDropdown.setEnabled(true);
    }//GEN-LAST:event_carMakerDropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | 
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountText;
    private javax.swing.JLabel carHomeLabel;
    private javax.swing.JComboBox carMakerDropdown;
    private javax.swing.JComboBox carModelDropdown;
    private javax.swing.JButton carmodelButton;
    private javax.swing.JLabel carpartnumberLabel;
    private javax.swing.JPanel chooseByCarModel;
    private javax.swing.JPanel chooseByVendor;
    private javax.swing.JLabel choosebycarmodelLabel;
    private java.awt.Panel choosecarPanel;
    private javax.swing.JLabel coreLabel;
    private javax.swing.JLabel coreText;
    private javax.swing.JComboBox engineDropDown;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homeScreenPage;
    private javax.swing.JLabel inconLabel;
    private javax.swing.JLabel inconText;
    private javax.swing.JLabel inheadLabel;
    private javax.swing.JLabel inheadText;
    private javax.swing.JLabel makerLabel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JButton nextButton;
    private java.awt.Panel nextButtonPanel;
    private javax.swing.JLabel oilcoolLabel;
    private javax.swing.JLabel oilcoolText;
    private javax.swing.JLabel ouconLabel;
    private javax.swing.JLabel ouconText;
    private javax.swing.JLabel outheadLabel;
    private javax.swing.JLabel outheadText;
    private javax.swing.JComboBox partNumberDropdown;
    private javax.swing.JLabel partnumberLabel;
    private javax.swing.JLabel partnumberText;
    private javax.swing.JComboBox partnumberdropdown;
    private javax.swing.JLabel partnumberdropdownLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceText;
    private javax.swing.JLabel searchbyLabel;
    private javax.swing.JLabel tmountLabel;
    private javax.swing.JLabel tmountText;
    private javax.swing.JButton vendorButton;
    private javax.swing.JComboBox vendorDropdown;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JPanel vendorLeftPanel;
    private javax.swing.JPanel vendorRightPanel;
    private javax.swing.JLabel vendordropdownLabel;
    private javax.swing.JComboBox yearDropdown;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables

    private void switchVisibility(JPanel componentToHide, JPanel componentToShow) {
        componentToHide.setVisible(false);
        componentToShow.setVisible(true);
    }
}
